### ISSUE TITLE
GPU not showing up

### ISSUE THREAD

**Issue by ItsMe-TJ** [Lenny4/DeepFaceLabClient#73] opened 2023-09-20 14:07 UTC
I decided to give this client a try, as I absolutely hate the .bat file system in regular DFL. 
I am however having an issue where the GPU won't show up, It's not saying that It can't detect a GPU, It's just loading forever with the blue spinning circle.

And yes, using regular DFL It asks me whether or not I want to use my CPU or GPU. I know other people had similar issues and that was a question you asked but never got a response.

**Comment by Lenny4** [comment] 2023-09-26 15:23
Hi @ItsMe-TJ 

Can you provide your system configuration ?

windows 10 ? 11 ? linux ?

**Comment by ItsMe-TJ** [comment] 2023-09-30 11:08
> Hi @ItsMe-TJ
> 
> Can you provide your system configuration ?
> 
> windows 10 ? 11 ? linux ?

Windows 11. 

System Specs, If you need them

RTX 3080
32GB RAM
AMD Ryzen 3950x

**Comment by Lenny4** [comment] 2023-09-30 15:25
@ItsMe-TJ 

Can you try this version and tell me if it solve the issue. Please note that the GPU may take up to 10s before showing up.

[Release.zip](https://github.com/Lenny4/DeepFaceLabClient/files/12775013/Release.zip)

**Comment by Lenny4** [comment] 2023-10-03 17:59
@ItsMe-TJ up

**Comment by Keyko716** [comment] 2023-10-06 06:01
i have the same issue 
i try your version it still happen  
"No CPG Detected on your machine" 
How Can i do

GTX4080 
i7_13700
64gb ram

> @ItsMe-TJ
> 
> Can you try this version and tell me if it solve the issue. Please note that the GPU may take up to 10s before showing up.
> 
> [Release.zip](https://github.com/Lenny4/DeepFaceLabClient/files/12775013/Release.zip)

**Comment by ItsMe-TJ** [comment] 2023-10-06 08:41
> @ItsMe-TJ
> 
> Can you try this version and tell me if it solve the issue. Please note that the GPU may take up to 10s before showing up.
> 
> [Release.zip](https://github.com/Lenny4/DeepFaceLabClient/files/12775013/Release.zip)

I tried this version, and It's still not detecting the GPU, I waited 2 minutes and It's just the spinning blue circle.

**Comment by Lenny4** [comment] 2023-10-06 12:09
> i have the same issue i try your version it still happen "No CPG Detected on your machine" How Can i do
> 
> GTX4080 i7_13700 64gb ram

If you got "No CPG Detected on your machine" it's not the same issue. @ItsMe-TJ has  just the spinning blue circle which never end. @Keyko716 open another issue please

**Comment by Lenny4** [comment] 2023-10-07 17:48
@ItsMe-TJ, can you try this Release please.
I did not solve the problem but this version will log what happen.

Once you start the app, go to Create a workspace and let the spinning circle spin for at least 20seconds.

Then go to the folder log
![image](https://github.com/Lenny4/DeepFaceLabClient/assets/25544892/5573ec4e-523a-4e45-8bbf-cb9f48cfc6ad)
which will be created after you run the app.

Inside you will find a file with the current date like this:
![image](https://github.com/Lenny4/DeepFaceLabClient/assets/25544892/92c96a2c-f447-4c01-a004-9ac086d89f18)

Please send me this file

[Release.zip](https://github.com/Lenny4/DeepFaceLabClient/files/12838405/Release.zip)

**Comment by ItsMe-TJ** [comment] 2023-10-09 13:27
> @ItsMe-TJ, can you try this Release please. I did not solve the problem but this version will log what happen.
> 
> Once you start the app, go to Create a workspace and let the spinning circle spin for at least 20seconds.
> 
> Then go to the folder log ![image](https://user-images.githubusercontent.com/25544892/273401063-5573ec4e-523a-4e45-8bbf-cb9f48cfc6ad.png) which will be created after you run the app.
> 
> Inside you will find a file with the current date like this: ![image](https://user-images.githubusercontent.com/25544892/273401097-92c96a2c-f447-4c01-a004-9ac086d89f18.png)
> 
> Please send me this file
> 
> [Release.zip](https://github.com/Lenny4/DeepFaceLabClient/files/12838405/Release.zip)

Here it is! Hope it helps!

[2023-10-09_15-24-34.925463.txt](https://github.com/Lenny4/DeepFaceLabClient/files/12846631/2023-10-09_15-24-34.925463.txt)

**Comment by Lenny4** [comment] 2023-10-11 00:27
We will try several things:

## first

Can you open a terminal and launch the command:

`E:\Deepfake\DeepFaceLab_NVIDIA_RTX3000_series\python-3.6.8\python.exe --version`

You should have the result `Python 3.6.8`.

![image](https://github.com/Lenny4/DeepFaceLabClient/assets/25544892/abebec54-3c96-48ea-a4d4-e2e723f310b8)

On the image I used my own path which is `C:\Users\alexa\Documents\_internal_directX12\python-3.6.8\python.exe --version` but you have to use `E:\Deepfake\DeepFaceLab_NVIDIA_RTX3000_series\python-3.6.8\python.exe --version`

Please send me a screenshot of your result

## second

Does `DeepFaceLabClient` and `DeepFaceLab_NVIDIA_RTX3000_series` are installed on the same disk ?

I see that `DeepFaceLab_NVIDIA_RTX3000_series` is on your `E` disk. Is `DeepFaceLabClient` also on `E` disk ?

Can you try to move `DeepFaceLab_NVIDIA_RTX3000_series` somewhere in your `C` disk and change the installation folder in DeepFaceLabClient

![image](https://github.com/Lenny4/DeepFaceLabClient/assets/25544892/f23c815f-08df-484b-810e-0f6dda1e13ad)

Tell me if you still have the problem

**Comment by ItsMe-TJ** [comment] 2023-10-16 10:47
> [<img alt="@Lenny4" width="40" height="40" src="https://avatars.githubusercontent.com/u/25544892?s=80&amp;u=7dd787fd82ec05415bb2d2b252b010ca6c04016f&amp;v=4">](/Lenny4)

Yes, both DeepFaceLab and DeepFaceLabClient are on the same disk.
Moving them both to the C drive didn't work.

![python](https://github.com/Lenny4/DeepFaceLabClient/assets/107994795/3098cfc8-c758-46ce-aba7-4fbe9aa5f180)

**Comment by Lenny4** [comment] 2023-10-16 14:01
Well I don't know how to fix this. I need access to your computer.

**Comment by nitatemic** [comment] 2023-12-10 11:41
I have the same issue

Windows 11 Pro 23H2
Intel 8700
RTX A4000 (Driver 546.01)

**Comment by Lenny4** [comment] 2023-12-11 12:06
@nitatemic 
- does it is loading forever with the blue spinning circle.
- or it says no gpu found
?

**Comment by Lenny4** [comment] 2024-03-06 12:28
I start working on this bug again because of https://github.com/Lenny4/DeepFaceLabClient/issues/77.

@ItsMe-TJ can you also try [test-fix-gpu-1.zip](https://github.com/Lenny4/DeepFaceLabClient/files/14503329/test-fix-gpu-1.zip) and tell me if it's solve the problem

**Comment by ItsMe-TJ** [comment] 2024-03-06 16:11
> I start working on this bug again because of #77.
> 
> @ItsMe-TJ can you also try [test-fix-gpu-1.zip](https://github.com/Lenny4/DeepFaceLabClient/files/14503329/test-fix-gpu-1.zip) and tell me if it's solve the problem

I gave it a try, and unfortuntely It's still just spinning forever.

**Comment by Lumerica** [comment] 2024-10-19 23:05
Hi I just was going to give this a try, and i have the same issue, blue endless spinning icon.

I'm on windows 10 gpu is 4090.
Can you tell me how to enable verbose mode so that I can see what its trying to do? it might give some hint.

**Comment by Lumerica** [comment] 2024-10-20 00:16
Have yet to figure out how DFL itself works so here I will say I **think** I found solution.

After monitoring the process what is happening I think I found the cause/solution.
It seems that the client does not make use of the environment bat file or something, i am not sure what is happening there as I would expect some more errors to appear. If the client uses the python/environment of the actual host instead of the environment in the DFL setenv.

So to solve this problem. First make sure you close and kill all python process because if you opened the client once and close it. There will still be a background process running that is in an endless loop trying to retrieve devices.

Then open CMD -> go to your DFL directory -> open setenv.bat
Then without closing the CMD screen (as the idea here is to have the environment variables needed for this client to use).
navigate to your DFL client directory within CMD and start the client executable and done.

In a nuttshell:
CMD:
`call <whatever drive +path to your DFL extract>\_internal\_internal\setenv.bat`
`<whatever drive + path to the DFL client>\DeepFaceLabClient.exe`

**Comment by Lenny4** [comment] 2024-10-20 18:34
What a god !

I will try to change the code so that `setenv.bat` will be use without having to call it in the cmd.

**Comment by Lenny4** [comment] 2024-10-20 20:31
@Lumerica 
@ItsMe-TJ 
@nitatemic 
@Keyko716 

Can you try
[DeepFaceLabClient-windows.zip](https://github.com/user-attachments/files/17452011/DeepFaceLabClient-windows.zip)

and tell me if the issue is solved ?

**Comment by Lumerica** [comment] 2024-10-20 23:08
@Lenny4 Works for me :)
Btw is it possible to add in the next release whenever you have time a way to log more details or perhaps in settings allowing the the debug/trace to be set to certain level in case of issues? :D

**Comment by Lenny4** [comment] 2024-10-21 06:06
@Lumerica maybe not in the next release but I will try to implement it soon

**Closed** 2024-10-21 08:41 UTC
Labels: bug, help wanted
