### ISSUE TITLE
Serious bug: Eternal blue wheel spinning without limit in the ''GPU'' section.

### ISSUE THREAD

**Issue by axxvj** [Lenny4/DeepFaceLabClient#78] opened 2024-08-22 12:21 UTC
Good morning. The problem is that when I open the interface, the GPU section stays with a blue circle spinning indefinitely. I have a NVIDIA 4000 (or 4020, and mi OS  Windows 11 , I don't remember exactly), and when I run ''face extraction'' or any other option, it opens a blank command console. I was very excited, I support the project, and would therefore appreciate a solution, since a wonderful project like this should be enjoyed. Thank you very much

Note: I have opened this thread because the solutions proposed in another thread with a similar case have not been valid, or I have not been able to apply them correctly due to lack of knowledge.

add photo: 
<img width="1907" alt="Captura de pantalla 2024-08-22 161934" src="https://github.com/user-attachments/assets/4603823d-0d3a-4551-8486-3fa5d7c6ac54">

**Comment by Lenny4** [comment] 2024-08-22 15:49
Hi @axxvj 

This problem exists for a while now

- https://github.com/Lenny4/DeepFaceLabClient/issues/77
- https://github.com/Lenny4/DeepFaceLabClient/issues/73

I can't fix this bug because i can't reproduce it on my machine as I do not have a graphical card.

To fix this we need someone who know how to code in Dart and also has the problem on his machine

Or I have to buy a graphical card but I don't have the money for it.

**Comment by axxvj** [comment] 2024-08-23 10:00
> Hola @axxvj
> 
> Este problema existe desde hace un tiempo
> 
> * [Installed RTX gpu #77](https://github.com/Lenny4/DeepFaceLabClient/issues/77)
> * [GPU not showing up #73](https://github.com/Lenny4/DeepFaceLabClient/issues/73)
> 
> No puedo corregir este error porque no puedo reproducirlo en mi máquina ya que no tengo una tarjeta gráfica.
> 
> Para arreglar esto necesitamos a alguien que sepa programar en Dart y que además tenga el problema en su máquina
> 
> O tengo que comprar una tarjeta gráfica pero no tengo el dinero para ello.

oh :( And I can do it from macOs? and from windows I can but without gpu?   Maybe one of those 2 options would solve the problem temporarily? Thanks

**Comment by Lenny4** [comment] 2024-09-16 23:16
Closing as duplicate

**Closed by Lenny4** 2024-09-16 23:16 UTC
